module PrepaidfactoryApi
  Error                              = Class.new(RuntimeError)

  ConnectionAuthenticationError      = Class.new(Error)
  ConnectionCertificateError         = Class.new(Error)
  ConnectionEndpointUnavailable      = Class.new(Error)
  ConnectionHTTPError                = Class.new(Error)
  ConnectionNoCertificate            = Class.new(Error)
  ConnectionNoCertificateKey         = Class.new(Error)
  ConnectionNoValidEndpointSpecified = Class.new(Error)
  ConnectionSSLError                 = Class.new(Error)

  OperationCancelOrderNotCancelable  = Class.new(Error)
  OperationCancelOrderNotFound       = Class.new(Error)
  OperationCancelOrderNotOpen        = Class.new(Error)
  OperationConfirmNotAllowed         = Class.new(Error)
  OperationGenericException          = Class.new(Error)
  OperationInvalidRequestType        = Class.new(Error)
  OperationMalformedRequest          = Class.new(Error)
  OperationNoCredit                  = Class.new(Error)
  OperationNotImplemented            = Class.new(Error)
  OperationOrderNotFound             = Class.new(Error)
  OperationOutOfStock                = Class.new(Error)
  OperationProductNotFound           = Class.new(Error)
  OperationRetailerNotFound          = Class.new(Error)
  OperationSOAPFault                 = Class.new(Error)
  OperationTerminalLimitExceeded     = Class.new(Error)
  OperationUnableToObjectify         = Class.new(Error)
  OperationUncaught                  = Class.new(Error)
  OperationUnknownOperation          = Class.new(Error)
  OperationUnknownRequestObject      = Class.new(Error)
  OperationUnknownResponseObject     = Class.new(Error)
  OperationUnknownStatus             = Class.new(Error)
  OperationWrongSetup                = Class.new(Error)
end
